### ISSUE TITLE
运行成功得不到任何数据

### ISSUE THREAD

**Issue by xingxing4182** [JiaoYanMoGu/indemind_data_collect#1]
你好，按照你的README配置运行后，运行成功了，终端上显示的是open successful,但在cam0和cam1文件夹，image.txt和imu.txt中都没有任何数据。我的摄像头usb接口是连接在3.0的口上的。希望得到您的答复

**Comment by JiaoYanMoGu** [comment]
这个程序是按照官方的Driver写的，我的笔记本ubuntu 16.04 USB2.0口跟你的情况一样，换USB3就行了，但是今天在台式机上试了一下，ubuntu18.04 系统，貌似扑街了，用官方的也不行，感觉问题可能是:1. 官方driver在18.04有问题 2. USB口有问题  所以你最好还是用官方的SDK吧

**Comment by JiaoYanMoGu** [comment]
> 你好，按照你的README配置运行后，运行成功了，终端上显示的是open successful,但在cam0和cam1文件夹，image.txt和imu.txt中都没有任何数据。我的摄像头usb接口是连接在3.0的口上的。希望得到您的答复

这个程序是按照官方的Driver写的，我的笔记本ubuntu 16.04 USB2.0口跟你的情况一样，换USB3就行了，但是今天在台式机上试了一下，ubuntu18.04 系统，貌似扑街了，用官方的也不行，感觉问题可能是:1. 官方driver在18.04有问题 2. USB口有问题 所以你最好还是用官方的SDK吧
